apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-app
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: arian-svirsky-resume
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ariansvi/ariansvi-resume-v2.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: resume
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
